### PR TITLE
XSD schema for cache2k xml configuration

### PR DESCRIPTION
**Pull request by Rokia88**
cache2k-xml-configuration/src/main/resources/cache2kv2.xsd is the proposed xsd for cache2k configuration. ( cache2k-xml-configuration/src/main/resources/cache2k.xsd is an additional xsd schema that looks like the xsd schema for ehcache configuration)
cache2k-xml-configuration/src/test/resources/ contains 3 additions xml instances for the proposed xsd schema

### CODE REVIEW

**Comment by cruftex** [comment]
Hi Rokia,

the XSD looks quite useful already!

Remarks:
- We do not check in the generated files like `sample5-xsdv21.xml`. As a general rule, never check in generated files. If we add or change names in the configuration, somebody has to edit these files, which will be painful.
- Add a small handcrafted XML file which contains every parameter once is fine.
- Add the XSD reference to the existing examples. Use a relative path.

Most tricky:
The configuration parser allows variables instead of the value, like `${env.hello}`, so the strict type checking will not work. Maybe the easiest and sufficient way for the first step is just to use "xs:string"?

**Comment by cruftex** [comment]
Please also add test cases that read in the XML files and check it against the schema.

**Comment by cruftex** [comment]
Just a announcement: I will restructure the code soon, probably you need to do a new PR with the new locations.

**Comment by Rokia88** [comment]
Hi Jens,
thanks for your feedback. I am not sure I have understood what I should do. So I will try to reformulate it, and please let me know if my understanding is correct or not:
1- I should delete the generated xml files sample 5, 6 and 7
2- I should create one valid instance file where every parameter is present. I should point to the xsd I have in the main folder using a relative path.
3- I should add a junit test where I read the xml file and validate it against the xsd schema.

**Comment by cruftex** [comment]
Looks better! If you have time please add descriptions. I am on holiday for one week now, not sure whether I will respond here during the next week.

**Comment by Rokia88** [comment]
ok. Thanks. I have added the unit test class, and some other xml instance files. So please let me know if anything need to be added/ modified.

**Comment by cruftex** [comment]
Hi @Rokia88, finally I put in the XSD schema. I went from your work as starting point, but did a lot of modifications. Most importantly, I decided not to copy the whole description of each parameter, but instead link to the documentation instead. For now this is easier for maintenance.

If interested, here it is:
https://github.com/cache2k/cache2k/blob/master/cache2k-schemas/src/main/resources/org/cache2k/schema/cache2k-core.xsd

Thanks for your contribution!

**Comment by Rokia88** [comment]
> Hi @Rokia88, finally I put in the XSD schema. I went from your work as starting point, but did a lot of modifications. Most importantly, I decided not to copy the whole description of each parameter, but instead link to the documentation instead. For now this is easier for maintenance.
> 
> If interested, here it is:
> https://github.com/cache2k/cache2k/blob/master/cache2k-schemas/src/main/resources/org/cache2k/schema/cache2k-core.xsd
> 
> Thanks for your contribution!

Hi @cruftex , sorry for my late reply. ok, great. 
thank you for giving me the opportunity to work on this project.

**Pull request closed without merging**
